rm -rf node_modules package-lock.json ./.cache; 

npm install --force --legacy-peer-deps --cache ./.cache \
@actions/core \
@actions/github \
@ag-grid-community/client-side-row-model \
@ag-grid-community/core \
@ag-grid-community/styles \
@angular-devkit/architect-cli \
@angular-devkit/build-angular \
@angular-devkit/core \
@angular-devkit/schematics \
@angular-devkit/schematics-cli \
@angular/animations \
@angular/build \
@angular/cdk \
@angular/cli \
@angular/common \
@angular/compiler \
@angular/compiler-cli \
@angular/core \
@angular/forms \
@angular/language-service \
@angular/localize \
@angular/material \
@angular/platform-browser \
@angular/platform-browser-dynamic \
@angular/platform-server \
@angular/router \
@angular/ssr \
@asymmetrik/leaflet-d3 \
@asymmetrik/ngx-leaflet  \
@asymmetrik/ngx-leaflet-d3 \
@asymmetrik/ngx-leaflet-markercluster \
@axe-core/playwright \
@babel/cli \
@babel/core \
@babel/generator \
@babel/plugin-proposal-async-generator-functions \
@bazel/bazelisk \
@bazel/buildifier \
@bazel/concatjs \
@bazel/esbuild \
@bazel/ibazel \
@bazel/jasmine \
@bazel/protractor \
@bazel/rollup \
@bazel/runfiles \
@bazel/terser \
@bazel/worker \
@bluehalo/ngx-leaflet \
@bluehalo/ngx-leaflet-draw \
@bluehalo/ngx-leaflet-markercluster \
@codemirror/autocomplete \
@codemirror/commands \
@codemirror/lang-angular \
@codemirror/lang-css \
@codemirror/lang-html \
@codemirror/lang-javascript \
@codemirror/lang-sass \
@codemirror/language \
@codemirror/lint \
@codemirror/search \
@codemirror/state \
@codemirror/view \
@docsearch/css \
@docsearch/js \
@emotion/react \
@emotion/styled \
@faker-js/faker \
@fontsource/roboto \
@fortawesome/fontawesome-free \
@inquirer/prompts \
@jridgewell/sourcemap-codec \
@lezer/common \
@lezer/highlight \
@lezer/javascript \
@maskito/angular \
@maskito/core \
@maskito/kit \
@maskito/phone \
@material-design-icons/svg \
@microsoft/api-extractor \
@mui/icons-material \
@mui/material \
@mui/x-charts \
@mui/x-data-grid \
@mui/x-date-pickers \
@ng-web-apis/common \
@ng-web-apis/intersection-observer \
@ng-web-apis/mutation-observer \
@ng-web-apis/platform \
@ng-web-apis/resize-observer \
@ng-web-apis/screen-orientation \
@ng-web-apis/universal \
@ng-web-apis/workers \
@nginfra/angular-linking \
@nguniversal/builders \
@nguniversal/express-engine \
@ngx-translate/core \
@ngx-translate/http-loader \
@novnc/novnc \
@nx/angular \
@nx/cypress \
@nx/devkit \
@nx/eslint \
@nx/jest \
@nx/js \
@nx/playwright \
@nx/web \
@nx/workspace \
@octokit/graphql \
@pbe/react-yandex-maps \
@playwright/test \
@rollup/plugin-babel \
@rollup/plugin-commonjs \
@rollup/plugin-node-resolve \
@schematics/angular \
@sentry/angular \
@stackblitz/sdk \
@swc-node/register \
@swc/core \
@swc/helpers \
@taiga-ui/addon-charts \
@taiga-ui/addon-commerce \
@taiga-ui/addon-doc \
@taiga-ui/addon-mobile \
@taiga-ui/addon-table \
@taiga-ui/browserslist-config \
@taiga-ui/cdk \
@taiga-ui/commitlint-config \
@taiga-ui/core \
@taiga-ui/cspell-config \
@taiga-ui/design-tokens \
@taiga-ui/dompurify \
@taiga-ui/editor \
@taiga-ui/eslint-plugin-experience \
@taiga-ui/eslint-plugin-experience-next \
@taiga-ui/event-plugins \
@taiga-ui/experimental \
@taiga-ui/i18n \
@taiga-ui/icons \
@taiga-ui/icons-fontawesome \
@taiga-ui/icons-material \
@taiga-ui/jest-config \
@taiga-ui/kit \
@taiga-ui/layout \
@taiga-ui/legacy \
@taiga-ui/polymorpheus \
@taiga-ui/prettier-config \
@taiga-ui/stylelint-config \
@taiga-ui/styles \
@taiga-ui/testing \
@taiga-ui/tsconfig \
@tailwindcss/aspect-ratio \
@tailwindcss/line-clamp \
@tailwindcss/postcss \
@tailwindcss/typography \
@testing-library/jest-dom \
@testing-library/react \
@testing-library/user-event \
@trivago/prettier-plugin-sort-imports \
@types/adm-zip \
@types/angular \
@types/babel__core \
@types/babel__generator \
@types/bcrypt \
@types/bluebird \
@types/chrome \
@types/cldrjs \
@types/convert-source-map \
@types/cookie-parser \
@types/cors \
@types/d3 \
@types/dom-navigation \
@types/dompurify \
@types/dotenv \
@types/express \
@types/glob \
@types/hammerjs \
@types/jasmine \
@types/jasmine-ajax \
@types/jasminewd2 \
@types/jest \
@types/jsdom \
@types/jsonwebtoken \
@types/leaflet  \
@types/leaflet \
@types/leaflet-draw \
@types/leaflet.markercluster \
@types/live-server \
@types/loader-utils \
@types/markdown-it \
@types/morgan \
@types/node \
@types/novnc__novnc \
@types/passport-jwt \
@types/pg \
@types/proj4 \
@types/react \
@types/react-dom \
@types/react-helmet \
@types/selenium-webdriver \
@types/semver \
@types/sequelize \
@types/shelljs \
@types/supertest \
@types/systemjs \
@types/tmp \
@types/uuid \
@types/validator \
@types/webpack-env \
@types/yargs \
@typescript-eslint/eslint-plugin \
@typescript-eslint/parser \
@typescript/vfs \
@vitejs/plugin-react \
@vitest/coverage-v8 \
@vitest/ui \
@webcontainer/api \
@xterm/addon-fit \
@xterm/xterm \
@yarnpkg/lockfile \
adm-zip \
ag-grid-react \
algoliasearch \
angular-split \
autoprefixer \
axe-playwright \
axios \
bcrypt \
body-parser \
canonical-path \
cesium \
chalk \
chart.js \
chartjs-plugin-zoom \
check-side-effects \
chokidar \
class-transformer \
class-validator \
cldr \
cldrjs \
conventional-changelog \
convert-source-map \
cookie-parser \
cors \
cpy-cli \
cypress \
cypress-image-diff-js \
cypress-plugin-tab \
cz-customizable \
d3 \
dagre-d3-es \
date-fns \
dayjs \
diff \
domino \
dompurify \
dotenv \
emoji-regex \
esbuild \
eslint \
eslint-config-prettier \
eslint-plugin-prettier \
eslint-plugin-react-hooks \
eslint-plugin-react-refresh \
eslint-plugin-unused-imports \
express \
fflate \
firebase-tools \
get-tsconfig \
gulp \
gulp-conventional-changelog \
hammerjs \
helmet \
html-entities \
http-server \
husky \
i \
ioredis \
jasmine \
jasmine-ajax \
jasmine-core \
jasmine-reporters \
jest \
jest-environment-jsdom \
jest-preset-angular \
jsdom \
jsonwebtoken \
jwt-decode \
karma \
karma-chrome-launcher \
karma-coverage \
karma-firefox-launcher \
karma-jasmine \
karma-jasmine-html-reporter \
karma-requirejs \
karma-sauce-launcher \
karma-sourcemap-loader \
leaflet
leaflet \
leaflet-draw \
leaflet-draw@1.0.2 \
leaflet.markercluster \
lint-staged \
live-server \
lucide-static \
magic-string \
markdown-it \
marked \
memo-decorator \
mermaid \
mobx \
mobx-react \
mobx-react-lite \
morgan \
ng-morph \
ng-packagr \
ng2-charts \
ngx-cookie-service-ssr \
ngx-flamegraph \
ngx-highlightjs \
ngx-progressbar \
nodemon \
npm \
nx \
open-in-idx \
parse5 \
passport \
passport-jwt \
patch-package \
pg \
pg-hstore \
pg-pool \
pino \
pino-http \
playwright-core \
postcss \
preact \
preact-render-to-string \
prettier \
prettier-plugin-organize-attributes \
prettier-plugin-tailwindcss \
proj4 \
protractor \
react \
react-dom \
react-helmet \
react-imask \
react-material-ui-carousel \
react-router-dom \
reflect-metadata \
requirejs \
resium \
resize-observer-polyfill \
rollup \
rollup-plugin-dts \
rollup-plugin-preserve-shebang \
rollup-plugin-sourcemaps \
rollup-plugin-sourcemaps2 \
rxjs \
safe-pipe \
sass \
selenium-webdriver \
semver \
semver-dsl \
sequelize \
sequelize-cli \
sequelize-typescript \
shelljs \
shiki \
socket.io \
socket.io-client \
source-map \
source-map-support \
standard-version \
supertest \
systemjs \
tailwindcss \
terser \
terser-webpack-plugin \
tinyglobby \
tmp \
todomvc-app-css \
todomvc-common \
ts-jest \
ts-mockito \
ts-node \
tsc-alias \
tsconfig-paths \
tsec \
tslib \
tslint \
tslint-eslint-rules \
tslint-no-toplevel-property-access \
tsx \
tus-js-client \
typed-graphqlify \
typescript \
typescript-eslint \
ua-parser-js \
undici \
uuid \
vite \
vite-plugin-cesium \
vite-tsconfig-paths \
vitest \
vrsource-tslint-rules \
webpack \
webtreemap \
ws \
xhr2 \
xng-breadcrumb \
yargs \
zone.js;

rm -rf node_modules package-lock.json ./.cache; 
